env: "local"
db:
  user-id: user
  password: password
  database: auth-service-db
  host: localhost
  options: Port=5432;Pooling=true
  migrations-path: "path"
grpc:
  port: 8080
  timeout: 1h
token:
  ttl: 10m