env: "prod"
db:
  user-id: user
  password: password
  database: auth-service-db
  host: database
  options: Port=5432;Pooling=true
  migrations-path: ""
grpc:
  port: 8080
  timeout: 1h
auth:
  token-ttl: 10m